apiVersion: batch/v1
kind: Job
metadata:
  name: hww-fm-jit
  labels:
    app: weavertagger
spec:
  template:
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger:latest
        command:
        - "/bin/bash"
        - "-c"
        - >
          git clone https://github.com/farakiko/weaver.git &&
          cd weaver &&
          (python make_jittable.py
          --data-config /hwwtaggervol/melissa-weaver/data/mq_ntuples/melissa_dataconfig_semilep_ttbarwjets.yaml
          -n networks/particle_net_pf_sv_4_layers_pyg_ef.py
          -m /hwwtaggervol/models/mq/05_10_ak8_ttbarwjets/05_10_ak8_ttbarwjets
          | tee /hwwtaggervol/log_farouk.txt)
        volumeMounts:
        - mountPath: /hwwtaggervol
          name: hwwtaggervol
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 64Gi
            cpu: "8"
            nvidia.com/gpu: "2"
          requests:
            memory: 12Gi
            cpu: "2"
            nvidia.com/gpu: "2"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/farakiko/weaver.git
          - /opt/repo/weaver
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: hwwtaggervol
        persistentVolumeClaim:
          claimName: hwwtaggervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-GTX-1080
                - NVIDIA-GeForce-GTX-1080-Ti
                - NVIDIA-GeForce-GTX-2080-Ti
      restartPolicy: Never
  backoffLimit: 0
        # resources:
        #   limits:
        #     memory: 140Gi
        #     cpu: "8"
        #     nvidia.com/gpu: "2"
        #   requests:
        #     memory: 128Gi
        #     cpu: "6"
        #     nvidia.com/gpu: "2"
