apiVersion: batch/v1
kind: Job
metadata:
  name: hww-fm-inference-jhu 
  labels:
    app: weavertagger
spec:
  template:
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger:latest
        command:
        - "/bin/bash"
        - "-c"
        - >
          git -C /hwwtaggervol/farouk-weaver pull &&
          mkdir -p /hwwtaggervol/inferences/fm/Oct_13_jhu &&
          mkdir -p /hwwtaggervol/plots/fm/Oct_13_jhu &&
          cd /opt/repo/weaver &&

          (python -u plots/plot_losses.py
          --model-path /hwwtaggervol/models/fm/Oct_10_jhu/Oct_10_jhu/
          --output /hwwtaggervol/plots/fm/Oct_13_jhu/losses.png
          | tee -a /hwwtaggervol/plots/fm/Oct_13_jhu/log.txt) &&

          (python -u train.py
          --predict
          --predict-output /hwwtaggervol/inferences/fm/Oct_13_jhu/hww.root
          --data-test '/hwwtaggervol/training/AK8_Sep16/test/GluGluHToWW_Pt-200ToInf_M-125/*.root'
          --data-config /hwwtaggervol/farouk-weaver/data/old_ntuples/ak8_mass_regression.yaml
          --network-config networks/particle_net_pf_sv_regression_4layer.py
          --model-prefix /hwwtaggervol/models/fm/Oct_10_jhu/_best_epoch_state.pt
          --gpus "0"
          --batch-size 256
          --fetch-step 0.02
          --num-workers 2
          --regression-mode
          | tee -a /hwwtaggervol/inferences/fm/Oct_13_jhu/log_hww.txt) &&

          (python -u train.py
          --predict
          --predict-output /hwwtaggervol/inferences/fm/Oct_13_jhu/jhu.root
          --data-test '/hwwtaggervol/training/AK8_Sep16/test/Bulk*/*.root'
          --data-config /hwwtaggervol/farouk-weaver/data/old_ntuples/ak8_mass_regression.yaml
          --network-config networks/particle_net_pf_sv_regression_4layer.py
          --model-prefix /hwwtaggervol/models/fm/Oct_10_jhu/_best_epoch_state.pt
          --gpus "0"
          --batch-size 256
          --fetch-step 0.02
          --num-workers 2
          --regression-mode
          | tee -a /hwwtaggervol/inferences/fm/Oct_13_jhu/log_jhu.txt)

        volumeMounts:
        - mountPath: /hwwtaggervol
          name: hwwtaggervol
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 64Gi
            cpu: "3"
            nvidia.com/gpu: "1"
          requests:
            memory: 32Gi
            cpu: "2"
            nvidia.com/gpu: "1"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/farakiko/weaver.git
          - /opt/repo/weaver
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: hwwtaggervol
        persistentVolumeClaim:
          claimName: hwwtaggervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-GTX-1080
                - NVIDIA-GeForce-GTX-1080-Ti
                - NVIDIA-GeForce-GTX-2080-Ti
      restartPolicy: Never
  backoffLimit: 0

          # (python -u plots/plot_classification_fromoutput.py
          # --name ParticleNet-PyG-EF
          # --ifile /hwwtaggervol/inferences/fm/Oct_13_jhu/qcd.root
          # --odir /hwwtaggervol/plots/fm/Oct_13_jhu/
          # --signals hww_elenuqq_merged,hww_elenuqq_semimerged,hww_munuqq_merged,hww_munuqq_semimerged,hww_taunuqq_merged,hww_taunuqq_semimerged
          # --bkgs qcd1lep,qcd1lep,qcd1lep,qcd1lep,qcd1lep,qcd1lep
          # --mbranch fj_genRes_mass
          # --jet AK8
          # -v
          # --isig /hwwtaggervol/inferences/fm/Oct_13_jhu/jhu.root,/hwwtaggervol/inferences/fm/Oct_13_jhu/hwwlnuqq.root
          # --isignames jhuSMHiggs,SMHiggs
          # | tee -a /hwwtaggervol/plots/fm/Oct_13_jhu/log.txt)


          # (python -u train.py
          # --predict
          # --predict-output /hwwtaggervol/inferences/fm/Oct_13_jhu/variableW.root
          # --data-test '/hwwtaggervol/training/AK8_Sep16/test/JHUVariableWMass*/*.root'
          # --data-config /hwwtaggervol/farouk-weaver/data/old_ntuples/ak8_mass_regression.yaml
          # --network-config networks/particle_net_pf_sv_regression_4layer.py
          # --model-prefix /hwwtaggervol/models/fm/Oct_10_jhu/Oct_10_jhu_best_epoch_state.pt
          # --gpus "0"
          # --batch-size 256
          # --fetch-step 0.02
          # --num-workers 2
          # --regression-mode
          # | tee -a /hwwtaggervol/inferences/fm/Oct_13_jhu/log_variableW.txt) &&

          # (python -u train.py
          # --predict
          # --predict-output /hwwtaggervol/inferences/fm/Oct_13_jhu/qcd.root
          # --data-test '/hwwtaggervol/training/AK8_Sep16/test/QCD*/*.root'
          # --data-config /hwwtaggervol/farouk-weaver/data/old_ntuples/ak8_mass_regression.yaml
          # --network-config networks/particle_net_pf_sv_regression_4layer.py
          # --model-prefix /hwwtaggervol/models/fm/Oct_10_jhu/Oct_10_jhu_best_epoch_state.pt
          # --gpus "0"
          # --batch-size 256
          # --fetch-step 0.02
          # --num-workers 2
          # --regression-mode
          # | tee -a /hwwtaggervol/inferences/fm/Oct_13_jhu/log_qcd.txt)
