apiVersion: batch/v1
kind: Job
metadata:
  name: hww-fm-train-jhu
  labels:
    app: weavertagger
spec:
  template:
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger:latest
        command:
        - "/bin/bash"
        - "-c"
        - >
          git -C /hwwtaggervol/farouk-weaver pull &&
          mkdir -p /hwwtaggervol/models/fm/Sep_30_jhu/ &&
          cd /opt/repo/weaver &&
          (python -u -W ignore train.py
          --data-train "/hwwtaggervol/training/AK8_Sep16/train/JHU*/*.root"
          --data-config /hwwtaggervol/farouk-weaver/data/old_ntuples/ak8_mass_regression.yaml
          --network-config networks/particle_net_pf_sv_regression_4layer.py
          --model-prefix /hwwtaggervol/models/fm/Sep_30_jhu/
          --num-workers 12
          --batch-size 256
          --num-epochs 40
          --start-lr 3e-3
          --optimizer ranger
          --gpu "0,1"
          --fetch-step 0.02
          --regression-mode
          | tee /hwwtaggervol/models/fm/Sep_30_jhu/log.txt)
        volumeMounts:
        - mountPath: /hwwtaggervol
          name: hwwtaggervol
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 140Gi
            cpu: "8"
            nvidia.com/gpu: "2"
          requests:
            memory: 128Gi
            cpu: "6"
            nvidia.com/gpu: "2"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://github.com/farakiko/weaver.git
          - /opt/repo/weaver
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: hwwtaggervol
        persistentVolumeClaim:
          claimName: hwwtaggervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-GTX-1080
                - NVIDIA-GeForce-GTX-1080-Ti
                - NVIDIA-GeForce-GTX-2080-Ti
      restartPolicy: Never
  backoffLimit: 0
        # resources:
        #   limits:
        #     memory: 140Gi
        #     cpu: "8"
        #     nvidia.com/gpu: "2"
        #   requests:
        #     memory: 128Gi
        #     cpu: "6"
        #     nvidia.com/gpu: "2"
